version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: chatbox
      POSTGRES_USER: chatbox
      POSTGRES_PASSWORD: dev_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://chatbox:dev_password@postgres:5432/chatbox?sslmode=disable
    depends_on:
      - postgres

volumes:
  postgres_data: